### PR TITLE
Properly display the description of each disease.

### PR DESCRIPTION
**Pull request by segun-adeleye**
PR with respect to this issue -> https://github.com/devcenter-square/disease-info-ui/issues/56

### CODE REVIEW

**Comment by yomete** [comment]
Hey @segun-adeleye Good one man.

Can you share a screenshot of your fix? 😄

**Comment by segun-adeleye** [comment]
Aight

#### Homepage
home-page


#### Disease Detail Page
disease-detail-page

**Comment by segun-adeleye** [comment]
Hey @yomete. I haven't heard back from you.

**Comment by AfolabiOlaoluwa** [comment]
@yomete however, you need to push to production to reflect changes on heroku production server and not only on the code base.

**Comment by yomete** [comment]
Done!

**Pull request merged**
