### PR TITLE
Fixed Web App Install Banner

### PR DESCRIPTION
**Pull request by juancuiule**
I have changed icon resolutions to match the criteria and have also updated routes in  the manifest.json
criteria

### CODE REVIEW

**Comment by yomete** [comment]
I'll look at now. Were you able to get the install web app banner?

**Comment by juancuiule** [comment]
Yes.
screenshot 11-49pm oct 26 2016

**Comment by yomete** [comment]
Whoop! Nice @juancuiule 
I'll merge now

**Comment by juancuiule** [comment]
Hi, do you know if this pull request will be counted to hacktoberfest? I forgot to add the hacktoberfest label...

**Comment by yomete** [comment]
Did you register for hacktoberfest before submitting the PR? If you did, then no worries about the tags. This project is under hacktoberfest.

**Comment by yomete** [comment]
Thank you for contributing 😀  😀

**Pull request merged**
