### PR TITLE
Added links to sections

### PR DESCRIPTION
**Pull request by joeinnes**
Hope this fits your needs - popped a UL at the top of the page, with links to each subheading.

### CODE REVIEW

**Comment by joeinnes** [comment]
Would close #21

**Comment by yomete** [comment]
I'll take a look at this and merge ASAP. Thanks @joeinnes

**Comment by osioke** [comment]
@yomete did this fix #21?

cc: @joeinnes

**Comment by yomete** [comment]
Nah, it didn't

**Comment by joeinnes** [comment]
The links would work with hashes, not slashes... The slashes would need to
be added to the router. I can give this a go too?

**Pull request merged**
