### PR TITLE
Added CONTRIBUTING.md and fixed README.md

### PR DESCRIPTION
**Pull request by AlexanderEllis**
#25  Added Contributing.md based off of disease-info contributing file with updated links and without the slack/license information.  I also fixed a typo in the readme and updated the link to contributing.md.

### CODE REVIEW

**Comment by osioke** [comment]
@AlexanderEllis why no reference to the project's discussion room, that is the Slack channel?

**Comment by AlexanderEllis** [comment]
@osioke I wasn't sure if you wanted that in here for the UI part as well, but I can add it.  Would you like the license at the bottom as well?

**Comment by osioke** [comment]
Thank you @AlexanderEllis that would be nice too :)

**Comment by AlexanderEllis** [comment]
Great!  I added that in my most recent commit.  Feel free to let me know if there is anything else you would like added.

**Pull request merged**
